### ISSUE TITLE
Handle case where vim and zsh are not installed on computer?

### ISSUE THREAD

**Issue by clemkoa** [vbrajon/dotfiles#1]
I tried to install dotfiles on a new distro, without zsh or vim. Maybe we should add a 

```
sudo apt-get install zsh
sudo apt-get install vim
```

 in the install script ?

**Comment by clemkoa** [comment]
@vbrajon also i have an error with badwolf theme. I think the repo vim-airline changed, and we should update the .vimrc file:

```
Plugin 'bling/vim-airline'
```

Should be:

```
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
```

They talk about it in this commit:
https://github.com/vim-airline/vim-airline/commit/d7fd8ca649e441b3865551a325b10504cdf0711b

I can make a pull request for this one :)

**Comment by vbrajon** [comment]
@clemkoa, I plan to update the install.sh script to add a dependency check.

Thanks for the input about vim-airline, I will patch this one line ;-).
